### ISSUE TITLE
Collisions not imported

### ISSUE THREAD

**Issue by rainbowlotus-games** [levigilbert/godot-LDtk-import#12]
I created a layer named "Collisions", and put down tiles in it, but I do not see any collision shapes imported in the game
(Clicking "Show collisions" on the TileMap doesn't reveal anything)

**Comment by DavidMag** [comment]
You have to go into the .import file and set it to true, should be located next to your ldtk file in your file explorer
<img width="174" alt="image" src="https://user-images.githubusercontent.com/22000931/128154200-04f824f9-e3dd-47a3-bb9c-52b2796a4fdc.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/22000931/128154320-435eca52-4b6a-4e8f-9647-5b6ae9bf438a.png">
