### ISSUE TITLE
Collisions preset not working.

### ISSUE THREAD

**Issue by tygutowski** [levigilbert/godot-LDtk-import#14]
The collisions preset does nothing. I have the preset enabled on the import tab, and in LDtk I've created a layer named "Collisions," but no colliders are generated when reimporting .ldtk file.

**Comment by levigilbert** [comment]
I just updated the collisions code and it should be working.

Currently how to use this feature:

1. Create an IntGrid layer named: "Collisions".
2. Place tiles in the layer where you want collision boxes.
3. Select your ldtk file in Godot and under the import tab check "Import Collisions".
