### ISSUE TITLE
Entity Import Discussion

### ISSUE THREAD

**Issue by univeous** [levigilbert/godot-LDtk-import#18]
Currently, entities without the `NodeType` field will be skipped for import.
I think this behavior needs some more discussion.
I would prefer to import it as a Node2d node and import all fields as metadata to be used by post-processing scripts.

Also currently, only custom fields are imported. I think it might be useful to import the non-custom fields (__tags etc.) together.

I will open a proposed PR later.

**Comment by levigilbert** [comment]
Defaulting to entities imported as Node2D's makes sense and I agree that importing the other fields as metadata would be useful.

Thanks!
