### ISSUE TITLE
i can't import ldtk file...

### ISSUE THREAD

**Issue by rebron1900** [levigilbert/godot-LDtk-import#2]
How to use it？

**Comment by levigilbert** [comment]
Copy the addons folder to your godot project folder.
Enable LDtk Importer under Project Settings/Plugins.
Add a .ldtk map file or use the example testmap.ldtk, the map will be imported as a .tscn file.

**Comment by rebron1900** [comment]
I tried to do this, but there is no content in the new scene file.

**Comment by levigilbert** [comment]
Looks like there's a new version of LDtk.  I'm working on updating the addon to support the new version.

**Comment by levigilbert** [comment]
I just updated the addon, should now work with the newest version of LDtk.  Please let me know if it works for you, thanks!

**Comment by rebron1900** [comment]
It started working，But not perfect yet
