### ISSUE TITLE
Let's collaborate

### ISSUE THREAD

**Issue by keir** [levigilbert/godot-LDtk-import#3]
Hi lgilbert,

I couldn't track down your contact info so this issue will have to do :)

Currently there are three Godot LDtk importers:
- Your importer (this repository)
- Josh Lee's importer - https://github.com/JoshLee0915/GodotLDtkImporter/
- My importer - https://github.com/keir/GodotLDtkImporter/ - which is a fork of Josh's but diverges substantially

When I first checked out your importer, it was not as far along, and then I made the mistake of not checking back when embarking on reworking Josh's importer for my own holiday game making. I suggested to Josh that we all work together here:

https://github.com/JoshLee0915/GodotLDtkImporter/issues/18 

I believe our entity handling is more sophisticated (we can instance user scenes), but your importer has a bunch of better aspects like proper unit testing.  If you want to chat realtime, I'm on the LDtk Discord, and my email is just my last name at gmail.

Cheers,
Keir

**Comment by levigilbert** [comment]
Haha, thanks for contacting me, definitely open to collaboration.  I’ll try to reach out via discord or email.
