### ISSUE TITLE
Relative paths error

### ISSUE THREAD

**Issue by Picalines** [levigilbert/godot-LDtk-import#5]
Godot couldn't load the TileSet texture. The bug turned out to be that the plugin specified the wrong path to the image.

Here's my file structure:
```
res://
  maps/
    test.ldtk
    tilesets/
      dungeon.png
```

In the `test.ldtk` file the relative path to `dungeon.png` was specified as `tilesets/dungeon.png`.

On the line 123 in the `LDtk.gd` Godot returns an error file 'res://tilesets/dungeon.png' not found.
```gdscript
#create new tileset from tileset_data.
func new_tileset(tileset_data):
	var tileset = TileSet.new()
	var texture_filepath = 'res://' + tileset_data.relPath
	var texture = load(texture_filepath) 
```

I fixed this bug by changing the value of the `texture_filepath` to:
```gdscript
var texture_filepath = map_data.base_dir + '/' + tileset_data.relPath
```

`map_data.base_dir` appears in the function `load_LDtk_file`:
```gdscript
#get LDtk file as JSON.
func load_LDtk_file(filepath):
    var json_file = File.new()
    json_file.open(filepath, File.READ)
    var json = JSON.parse(json_file.get_as_text()).result
    json_file.close()

    json['base_dir'] = filepath.get_base_dir()

    return json
```

After that, everything worked.

P.S.
sorry for my broken english

**Comment by levigilbert** [comment]
Thank you, I've updated the code to fix the issue.

Also your english is very good!
