### ISSUE TITLE
sample ldtk file import not correct

### ISSUE THREAD

**Issue by JustusPan** [levigilbert/godot-LDtk-import#8]
godot 3.3
ldtk 0.9.3 and ldtk 0.8.x

Following official sample from ldtk could not be imported correctly in godot.

[Typical_TopDown_example.zip](https://github.com/lrgilbert/godot-LDtk-import/files/6489389/Typical_TopDown_example.zip)

**Comment by JustusPan** [comment]
maybe it's related to 'tile stacking' mode of ldtk

**Comment by levigilbert** [comment]
I'm working on updating the plugin. I haven't been maintaining it due to life.

The current plan is to get the basic features working with the latest versions of Godot and LDtk. Then I'll be filling out the newer features of LDtk and trying to add further functionality.
